version: '3.2'

services:
  web:
    image: hio_api
    container_name: hio_api
    networks:
      backend:
        aliases:
          - hio_api
    restart: always
    ports:
      - 5010:8360
    build:
      context: ./docker/
      dockerfile: Dockerfile

networks:
  backend:
    driver: bridge
