version: '3.2'

services:
  hio_api:
    image: hio_api
    container_name: hio_api
    restart: always
    networks:
      backend:
        aliases:
          - hio_api
    ports:
      - 5010:8360
    build:
      context: .
      dockerfile: docker/Dockerfile
  hio_db:
    image: mysql:8.0.26
    container_name: hio_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      backend:
        aliases:
          - hio_db
    ports:
      - 5009:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456789

networks:
  backend:
    driver: bridge
